### ISSUE TITLE
s_resolution_beam_dirty  (From John Tobin)

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/ObsCoreExtensionForRadioData#16]
**From John Tobin**

s_resolution_beam_dirty - it is unclear what is intended here, whether it's to be a map of the dirty beam or the resolution of the dirty beam. If it's the resolution, this is somewhat redundant because the resolution of a cleaned map is derived from a Gaussian fit to the central core of the dirty beam, and there would be a degeneracy with what is provided by s_resolution. The dirty beam image, or psf image as CASA refers to it, is not always archived. ALMA and the NRAO do not include it in their standard image products for instance, so it is unclear how readily available this information would be for most archives.

**Comment by Bonnarel** [comment]
> **From John Tobin**
> 
> s_resolution_beam_dirty - it is unclear what is intended here, whether it's to be a map of the dirty beam or the resolution of the dirty beam. If it's the resolution, this is somewhat redundant because the resolution of a cleaned map is derived from a Gaussian fit to the central core of the dirty beam, and there would be a degeneracy with what is provided by s_resolution. The dirty beam image, or psf image as CASA refers to it, is not always archived. ALMA and the NRAO do not include it in their standard image products for instance, so it is unclear how readily available this information would be for most archives.

From François Bonnarel : 

Obviously the idea was to add a FIELD containing a link to the dirty beam map. The idea was to display it to help the user to figure out the level of quality of data. And this not a queryable column of course.

**Comment by kettenis** [comment]
Is this something that might be better done using DataLink?

**Comment by Bonnarel** [comment]
Le 28/08/2023 à 15:05, kettenis a écrit :
>
> Is this something that might be better done using DataLink?
>
For sure DataLink would work for that.

As for the ObsCore extension such integratin of dirty beam in the table  
would provide an official name/utype

**Comment by Bonnarel** [comment]
This change has been introduced in the text wth PR
