### ISSUE TITLE
2 files . tex with same name on different branches 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/ObsCoreExtensionForRadioData#42]
I guess we should rename the .tex file for uses cases like ADQL_uses_cases.tex  not to collapse with the main text  .
when the appendix is ready it can be included with 
 \include{ADQL_uses_cases} in the Obscore extension specification .

**Comment by Bonnarel** [comment]
The main branch now includes the appendix file with the ADQL use cases. It is now called in the main latex file. The other branch has been suppressed t avid confusion

**Comment by Bonnarel** [comment]
issue solved
